name: PluginSB
version: '${project.version}'
main: me.lavarite.pluginsb.Items.PluginSB
api-version: 1.18
commands:
  giveItem:
    description: Gives Specified Item/-s to the player.
    usage: /<command> <Item>